language: c
compiler: gcc
sudo: false
script:
        - touch COPYRIGHT sntp/scm-rev
        - ./bootstrap
        - ./build
        - ls
        - cat $(find . -name "make.log")
        - cd $(find . -name "A.*")
        - make
        - make check
        - make distcheck
        - ls ..
