language: c
compiler: 
        - gcc
        - clang
addons:
    apt:
        packages:
            - clang-3.6
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
script:
        - wget https://people.debian.org/~aurel32/qemu/powerpc/debian_wheezy_powerpc_standard.qcow2
        - sudo apt-get update
        - sudo apt-get install qemu-system -y
        - sudo apt-get install qemu-system-x86 -y
        - wget ftp://ftp.stacklet.com/archive/x86-64/FreeBSD/9.2/freebsd.9-2.x86-64.20140103.raw.img.txz
        - tar -xvf freebsd.9-2.x86-64.20140103.raw.img.txz
        - qemu-system-x86_64 -hda freebsd.9-2.x86-64.20140103.raw.img
        - if [ "$CC" = "clang" ]; then export CC=clang-3.6; fi
        - echo $($CC --version)
        - touch COPYRIGHT sntp/scm-rev
        - ./bootstrap
        - ./build --enable-local-libevent
        - cat $(find . -name "make.log")
        - cd $(find . -name "A.*")
        - make
        - make check
        - make distcheck
