language: c
compiler: gcc
before_install: 
        - sudo apt-get install -y lynx
        - alias bk=echo
script:
        - ./bootstrap
        - ./build
        - ls
        - cat $(find . -name "make.log")
        - cd $(find . -name "A.*")
        - make
        - make check
        - make distcheck
