language: c
compiler: 
        - gcc
        - clang
sudo: false
addons:
    apt:
        packages:
            - clang
script:
        - touch COPYRIGHT sntp/scm-rev
        - ./bootstrap
        - ./build --enable-local-libevent
        - ls
        - cat $(find . -name "make.log")
        - cd $(find . -name "A.*")
        - make
        - make check
        - make distcheck
        - ls ..
