language: c
compiler: 
        - gcc
        - clang
sudo: false
addons:
    apt:
        packages:
            - clang-3.6
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
script:
        - if [ "$CC" = "clang" ]; then export CC=clang-3.6; fi
        - echo $($CC --version)
        - touch COPYRIGHT sntp/scm-rev
        - ./bootstrap
        - ./build --enable-local-libevent
        - cat $(find . -name "make.log")
        - cd $(find . -name "A.*")
        - make
        - make check
        - make distcheck
env:
        - STH=true
        - STH=false
        - STH2=true
        - STH2=false
        - STH3=true
        - STH4=false
        - STH5=true
        - STH5=false
