language: c
compiler: gcc
script:
        - ./bootstrap
        - ./build
        - ls
        - cat $(find . -name "make.log")
        - cd $(find . -name "A.*")
        - make
        - make check
        - make distcheck
        - ls ..
