language: c
compiler: 
        - gcc
addons:
    apt:
        packages:
            - clang-3.6
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
script:
        - wget https://people.debian.org/~aurel32/qemu/powerpc/debian_wheezy_powerpc_standard.qcow2
        - sudo apt-get update
        - sudo apt-get install qemu-system -y
        - sudo apt-get install expect -y
        - df -h
        - wget ftp://ftp.stacklet.com/archive/x86-64/FreeBSD/9.2/freebsd.9-2.x86-64.20140103.raw.img.txz
        - tar -xvf freebsd.9-2.x86-64.20140103.raw.img.txz
        - sudo qemu-system-x86_64 -hda freebsd.9-2.x86-64.20140103.raw.img -net user -net nic -redir tcp:4941:10.0.2.15:22 -display none -daemonize
        - sleep 180
        - expect -f expect_scp
        - expect -f expect_freebsd
        - exit 