language: c
compiler: gcc
sudo: false
script:
        - ./bootstrap
        - ./build
        - ls
        - cat $(find . -name "make.log")
        - cd $(find . -name "A.*")
        - make -j3
        - make check -j3
        - make distcheck
        - ls ..
