language: c
compiler: 
        - gcc
        - clang
addons:
    apt:
        packages:
            - clang-3.6
            - qemu
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
script:
        - wget https://people.debian.org/~aurel32/qemu/mips/debian_wheezy_mips_standard.qcow2
        - sudo apt-get install qemu -y
        - if [ "$CC" = "clang" ]; then export CC=clang-3.6; fi
        - echo $($CC --version)
        - touch COPYRIGHT sntp/scm-rev
        - ./bootstrap
        - ./build --enable-local-libevent
        - cat $(find . -name "make.log")
        - cd $(find . -name "A.*")
        - make
        - make check
        - make distcheck
